-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg6+lEJoPpYObSXmZq
ZNMzCz6MTn7E/uFrnhyTzHr/0VegCgYIKoZIzj0DAQehRANCAARUaVQbmiaKuQcp
lKRTgcSmiVY3GNpOBDXbkAKh7XstSHGtFWPe8HPGFHmoy2tgw5y8RAy/RTt/Jqmu
SK1kYcld
-----END PRIVATE KEY-----